package com.example.webrtcmeet

object Constants {
    const val USERS_COLLECTION = "users"
    const val ERROR_TEXT = "Some error has occurred"
    const val API_BASE_URL = "https://randomuser.me/"
    const val UID = "uid"
    const val PHOTO_URL = "photoUrl"
    const val DISPLAY_NAME = "displayName"
    const val CALLS_COLLECTION = "calls"
    const val SDP = "sdp"
    const val TYPE = "type"
    const val SDP_MID = "sdpMid"
    const val SDP_MLINEINDEX = "sdpMLineIndex"
    const val ANSWER_CANDIDATE = "answerCandidate"
    const val OFFER_CANDIDATE = "offerCandidate"
    const val SDP_CANDIDATE = "sdpCandidate"
    const val SERVER_URL = "serverUrl"
    const val CANDIDATES_COLLECTION = "candidates"
    const val ALL_USERS_COLLECTION = "allUsers"
    const val END_CALL = "END_CALL"
    const val OFFER = "OFFER"
    const val ANSWER = "ANSWER"
    const val MEETING_ID = "meetingID"
    const val IS_JOIN = "isJoin"
    const val RETURN_FROM_CALL = "returnFromCall"
}